
[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "mon-bagage"
  name = "Mon Bagage"
  url = "showcase"
  weight = 3

[[main]]
  identifier = "publication"
  name = "Publications"
  url = "publication"
  weight = 4

[[main]]
  identifier = "a-propos"
  name = "À propos"
  url = "a-propos"
  weight = 5

[[main]]
  identifier = "contact"
  name = "Contactez-moi"
  url = "contactez-moi"
  weight = 6

# #  vim: set sts=2 ts=2 sw=2 tw=120 et :

