
[[main]]
  identifier = "arkivo"
  name = "Arkivo"
  url = "arkivo"
  weight = 2

[[main]]
  identifier = "laborajxoj"
  name = "Mia laboraĵlisto"
  url = "showcase"
  weight = 2

[[main]]
  identifier = "eldonoj"
  name = "Eldonoj"
  url = "publication"
  weight = 3

[[main]]
  identifier = "pri"
  name = "Pri mi"
  url = "pri"
  weight = 5

[[main]]
  identifier = "kontakto"
  name = "Kontaktu min"
  url = "kontaktu-min"
  weight = 6

#  vim: set sts=2 ts=2 sw=2 tw=120 et :

